name: date_app
description: "A Flutter project for matching based on music, movies, and books preferences."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_web_auth: ^0.5.0
  provider: ^6.0.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  url_launcher: ^6.1.7
  app_links: ^6.3.2
  crypto: ^3.0.5
  flutter_web_auth_2: ^3.1.2
  oauth2: ^2.0.3
  uni_links2: ^0.6.0+2



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Varlıklar ve resimler buraya eklenebilir
  # assets:
  #   - images/logo.png

  # Özel fontlar eklemek isterseniz:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
